In [136]:
using CSV
using DataFrames
using GLM
using Optim
using Statistics
using ForwardDiff
using NLopt

# The Nerlove Model

### Theoretical Background
For a firm that takes input prices $w$ and the output level $q$
as given, the cost minimization problem is to choose the quantities
of inputs $x$ to solve the problem
$$
\min_{x}w'x
$$
 subject to the restriction
$$
f(x)=q.
$$
 The solution is the vector of factor demands $x(w,q)$. The cost
function is obtained by substituting the factor demands into the
criterion function: 
$$
Cw,q)=w'x(w,q).
$$
 
- **Monotonicity** Increasing factor prices cannot decrease cost, so 
$$\frac{\partial C(w,q)}{\partial w}\geq0$$
Remember that these derivatives give the conditional factor demands
(Shephard's Lemma).
- **Homogeneity** The cost function is homogeneous of degree 1 in input prices: $C(tw,q)=tC(w,q)$ where $t$ is a scalar constant. This is because the factor demands are homogeneous of degree zero in factor prices - they only depend upon relative prices.
- **Returns to scale** The returns to scale parameter $\gamma$ is defined as the inverse of the elasticity of cost with respect to output:
$$
\gamma=\left(\frac{\partial C(w,q)}{\partial q}\frac{q}{C(w,q)}\right)^{-1}
$$
Constant returns to scale is the case where increasing production
$q$ implies that cost increases in the proportion 1:1. If this is
the case, then $\gamma=1$.

#### Cobb-Douglas functional form

The Cobb-Douglas functional form is linear in the logarithms of the
regressors and the dependent variable. For a cost function, if there
are $g$ factors, the Cobb-Douglas cost function has the form

$$
C=Aw_{1}^{\beta_{1}}...w_{g}^{\beta_{g}}q^{\beta_{q}}e^{\varepsilon}
$$
What is the elasticity of $C$ with respect to $w_{j}$?
\begin{eqnarray*}
e_{w_{j}}^{C} & = & \left(\frac{\partial C}{\partial_{W_{J}}}\right)\left(\frac{w_{j}}{C}\right)\\
 & = & \beta_{j}Aw_{1}^{\beta_{1}}.w_{j}^{\beta_{j}-1}..w_{g}^{\beta_{g}}q^{\beta_{q}}e^{\varepsilon}\frac{w_{j}}{Aw_{1}^{\beta_{1}}...w_{g}^{\beta_{g}}q^{\beta_{q}}e^{\varepsilon}}\\
 & = & \beta_{j}
\end{eqnarray*}
This is one of the reasons the Cobb-Douglas form is popular - the
coefficients are easy to interpret, since they are the elasticities
of the dependent variable with respect to the explanatory variable.
Not that in this case,
\begin{eqnarray*}
e_{w_{j}}^{C} & = & \left(\frac{\partial C}{\partial_{W_{J}}}\right)\left(\frac{w_{j}}{C}\right)\\
 & = & x_{j}(w,q)\frac{w_{j}}{C}\\
 & \equiv & s_{j}(w,q)
\end{eqnarray*}
the cost share of the $j^{th}$ input. So with a Cobb-Douglas
cost function, $\beta_{j}=s_{j}(w,q)$. The cost shares are constants.

Note that after a logarithmic transformation we obtain
$$
\ln C=\alpha+\beta_{1}\ln w_{1}+...+\beta_{g}\ln w_{g}+\beta_{q}\ln q+\epsilon
$$
where $\alpha=\ln A$ . So we see that the transformed model is linear
in the logs of the data.

One can verify that the property of HOD1 implies that 
$$
\sum_{i=1}^{g}\beta_{i}=1
$$
In other words, the cost shares add up to 1. 

The hypothesis that the technology exhibits CRTS implies that 
$$
\gamma=\frac{1}{\beta_{q}}=1
$$
so $\beta_{q}=1.$ Likewise, monotonicity implies that the coefficients
$\beta_{i}\geq0,i=1,...,g$.


### The Nerlove Data
The file contains data on 145 electric utility companies' cost of production,
output and input prices. The data are for the U.S., and were collected
by M. Nerlove. The observations are by row, and the columns are 
- COMPANYCOST $(C)$
- OUTPUT $(Q)$ 
- PRICE OF LABOR $(P_{L})$
- PRICE OF FUEL $(P_{F})$
- PRICE OF CAPITAL$(P_{K})$ 

Note that the data are sorted by output level (the third column).

We will estimate the Cobb-Douglas model 
$$\ln C=\beta_{1}+\beta_{Q}\ln Q+\beta_{L}\ln P_{L}+\beta_{F}\ln P_{F}+\beta_{K}\ln P_{K}+\epsilon\label{simple nerlove model}
$$ by OLS.


In [137]:
data = DataFrame(CSV.File("../data/nerlove.csv"))
first(data,6)

6×6 DataFrame
 Row │ firm   cost     output  labor    fuel     capital 
     │ Int64  Float64  Int64   Float64  Float64  Int64   
─────┼───────────────────────────────────────────────────
   1 │   101    0.082       2     2.09     17.9      183
   2 │   102    0.661       3     2.05     35.1      174
   3 │   103    0.99        4     2.05     35.1      171
   4 │   104    0.315       4     1.83     32.2      166
   5 │   105    0.197       5     2.12     28.6      233
   6 │   106    0.098       9     2.12     28.6      195

In [138]:
data = log.(data[:,[:cost,:output,:labor,:fuel,:capital]])
first(data,6)

6×5 DataFrame
 Row │ cost        output    labor     fuel     capital 
     │ Float64     Float64   Float64   Float64  Float64 
─────┼──────────────────────────────────────────────────
   1 │ -2.50104    0.693147  0.737164  2.8848   5.20949
   2 │ -0.414001   1.09861   0.71784   3.5582   5.15906
   3 │ -0.0100503  1.38629   0.71784   3.5582   5.14166
   4 │ -1.15518    1.38629   0.604316  3.47197  5.11199
   5 │ -1.62455    1.60944   0.751416  3.35341  5.45104
   6 │ -2.32279    2.19722   0.751416  3.35341  5.273

In [139]:
n = size(data,1)
y = data[:,1]
x = data[:,2:end]
x[!,:intercept]=ones(size(data,1))
x = x[!,[:intercept,:output,:labor,:fuel,:capital]]

y = convert(Array,y)
x = convert(Array,x)

145×5 Array{Float64,2}:
 1.0  0.693147  0.737164  2.8848   5.20949
 1.0  1.09861   0.71784   3.5582   5.15906
 1.0  1.38629   0.71784   3.5582   5.14166
 1.0  1.38629   0.604316  3.47197  5.11199
 1.0  1.60944   0.751416  3.35341  5.45104
 1.0  2.19722   0.751416  3.35341  5.273
 1.0  2.3979    0.683097  3.56953  5.32788
 1.0  2.56495   0.71784   3.5582   5.01064
 1.0  2.56495   0.783902  3.37074  5.04343
 1.0  3.09104   0.542324  2.70805  5.23644
 1.0  3.21888   0.737164  2.8848   5.1358
 1.0  3.21888   0.518794  3.68135  5.11799
 1.0  3.55535   0.593327  3.11795  5.36129
 ⋮                                 
 1.0  8.72193   0.652325  3.11352  5.07517
 1.0  8.88086   0.751416  3.35341  5.0876
 1.0  8.97284   0.476234  2.8792   5.18178
 1.0  9.03825   0.841567  3.46261  5.2933
 1.0  9.06439   0.806476  3.27714  5.20401
 1.0  9.08103   0.837248  3.51155  5.24702
 1.0  9.15736   0.746688  3.19458  5.10595
 1.0  9.20593   0.518794  3.36038  5.31321
 1.0  9.3481    0.806476  3.27714  5.01728

In [140]:
inv(x'*x)*x'*y

5-element Array{Float64,1}:
 -3.5265028449802216
  0.7203940758797012
  0.4363412007892406
  0.4265169530627446
 -0.2198883507567723

## OLS

In [141]:
ols = lm(@formula(cost~output+labor+fuel+capital),data)

StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Array{Float64,1}},GLM.DensePredChol{Float64,LinearAlgebra.CholeskyPivoted{Float64,Array{Float64,2}}}},Array{Float64,2}}

cost ~ 1 + output + labor + fuel + capital

Coefficients:
──────────────────────────────────────────────────────────────────────────
                 Coef.  Std. Error      t  Pr(>|t|)  Lower 95%   Upper 95%
──────────────────────────────────────────────────────────────────────────
(Intercept)  -3.5265     1.77437    -1.99    0.0488  -7.03452   -0.0184845
output        0.720394   0.0174664  41.24    <1e-79   0.685862   0.754926
labor         0.436341   0.291048    1.50    0.1361  -0.139076   1.01176
fuel          0.426517   0.100369    4.25    <1e-4    0.228082   0.624952
capital      -0.219888   0.339429   -0.65    0.5182  -0.890957   0.45118
──────────────────────────────────────────────────────────────────────────

## MLE

In [142]:
function fminunc(obj, x; tol = 1e-08)
results = Optim.optimize(obj, x, LBFGS(),
Optim.Options(
g_tol = tol,
x_tol=tol,
f_tol=tol))
return results.minimizer, results.minimum, Optim.converged(results)
#xopt, objvalue, flag = fmincon(obj, x, tol=tol)
#return xopt, objvalue, flag
end

fminunc (generic function with 1 method)

In [143]:
function normal(theta, y, x)
b = theta[1:end-1]
s = theta[end][1]
e = (y - x*b)./s
logdensity = -log.(sqrt.(2.0*pi)) .- 0.5*log(s.^2) .- 0.5*e.*e
end

normal (generic function with 1 method)

In [144]:
function mle(model, θ)
    avg_obj = θ -> -mean(vec(model(θ))) # average log likelihood
    thetahat, objvalue, converged = fminunc(avg_obj, θ) # do the minimization of -logL
    objvalue = -objvalue
    obj = θ -> vec(model(θ)) # unaveraged log likelihood
    n = size(obj(θ),1) # how many observations?
    scorecontrib = ForwardDiff.jacobian(obj, vec(thetahat))
    I = cov(scorecontrib)
    J = ForwardDiff.hessian(avg_obj, vec(thetahat))
    Jinv = inv(J)
    V= Jinv*I*Jinv/n
    return thetahat, objvalue, V, converged
end

mle (generic function with 1 method)

In [145]:
theta = [zeros(size(x,2)); 1.0] # start values for estimation
model = theta -> normal(theta, y, x)
thetahat, objvalue, V, converged = mle(model, theta)

([-3.5265029527984506, 0.7203941307911956, 0.4363410601373892, 0.4265167999256887, -0.21988830342608368, 0.3855314736645991], -0.4658061612351275, [2.871544188031368 -0.013350664827278202 … -0.5341833292561572 0.00758992898888696; -0.01335066482727622 0.0010330820163605126 … 0.0014703347896175387 -0.000888618606090073; … ; -0.5341833292561352 0.0014703347896179168 … 0.10194167672632491 -0.0009345831820626936; 0.00758992898888676 -0.000888618606090018 … -0.0009345831820626361 0.0017343512126735234], true)

In [146]:
thetahat

6-element Array{Float64,1}:
 -3.5265029527984506
  0.7203941307911956
  0.4363410601373892
  0.4265167999256887
 -0.21988830342608368
  0.3855314736645991

In [147]:
objvalue

-0.4658061612351275

In [148]:
converged

true

## GMM

In [149]:
function gmm(moments, theta, weight)
    # average moments
    m = theta -> vec(mean(moments(theta),dims=1)) # 1Xg
    # moment contributions
    momentcontrib = theta -> moments(theta) # nXg
    # GMM criterion
    obj = theta -> ((m(theta))'weight*m(theta))
    # do minimization
    thetahat, objvalue, converged = fminunc(obj, theta)
    # derivative of average moments
    D = (ForwardDiff.jacobian(m, vec(thetahat)))' 
    # moment contributions at estimate
    ms = momentcontrib(thetahat)
    return thetahat, objvalue, D, ms, converged
end

gmm (generic function with 1 method)

In [160]:
vec(mean(moments(theta),dims=1))

5-element Array{Float64,1}:
  1.7246632842783778
 13.884929436866436
  1.178851571114924
  5.511122653204082
  8.878930381596613

In [163]:
weight = 1
theta = zeros(size(x,2))
moments = theta -> (y .- x*theta).*x
thetahat1, junk, junk, ms, junk = gmm(moments, theta, weight)

([-3.526502843629834, 0.7203940758779137, 0.4363412007234413, 0.4265169530669924, -0.21988835101027032], 2.0315912495823984e-25, [-1.0 -6.556651068379128 … -3.2088584232140143 -5.15677677573767; -6.556651068379128 -46.62321518989734 … -20.92418272643975 -33.79234977799892; … ; -3.2088584232140143 -20.92418272643975 … -10.424693444784769 -16.552050639682335; -5.15677677573767 -33.79234977799892 … -16.552050639682335 -26.60235530942714], [0.11956154515690232 0.08287374792889741 … 0.3449112306976858 0.622854213907207; 1.6246276007326357 1.7848358466742609 … 5.780751765522584 8.38154363280989; … ; 0.8830924883738982 8.453078045568063 … 3.1010193996152986 4.730361102489577; 0.7151025229149148 6.953872233201762 … 2.260615499330251 3.6381529748973525], true)

In [165]:
thetahat1

5-element Array{Float64,1}:
 -3.526502843629834
  0.7203940758779137
  0.4363412007234413
  0.4265169530669924
 -0.21988835101027032

In [164]:
W = inv(cov(ms))
thetahat2, junk, junk, ms, junk = gmm(moments, theta, W)

([-3.526502845237955, 0.7203940758869178, 0.43634120077645283, 0.42651695306397513, -0.21988835071590623], 4.523502175795952e-22, [-1.0 -6.556651068379128 … -3.2088584232140143 -5.15677677573767; -6.556651068379128 -46.62321518989734 … -20.92418272643975 -33.79234977799892; … ; -3.2088584232140143 -20.92418272643975 … -10.424693444784769 -16.552050639682335; -5.15677677573767 -33.79234977799892 … -16.552050639682335 -26.60235530942714], [0.11956154519492257 0.08287374795525106 … 0.34491123080736663 0.6228542141052729; 1.6246276007849059 1.7848358467316856 … 5.7807517657085725 8.381543633079556; … ; 0.8830924882852536 8.453078044719545 … 3.1010193993040187 4.730361102014744; 0.7151025229032566 6.953872233088394 … 2.2606154992933964 3.63815297483804], true)

In [166]:
thetahat2

5-element Array{Float64,1}:
 -3.526502845237955
  0.7203940758869178
  0.43634120077645283
  0.42651695306397513
 -0.21988835071590623